model:
  encoder:
    node_embed_size: 128
    edge_embed_size: 64
    ipa:
      c_s: 128 #${model.node_embed_size}
      c_z: 64 #${model.edge_embed_size}
      c_hidden: 128
      no_heads: 8
      no_qk_points: 8
      no_v_points: 12
      seq_tfmr_num_heads: 4
      seq_tfmr_num_layers: 2
      num_encoder_blocks: 4
      num_decoder_blocks: 4
      stop_grad: False
      codebook_size: 512
      # codebook_dim: 32
      commitment_cost: 0.25
      init_steps: 50000
      collect_desired_size: 9000
      scales: 8

par:
  depth: 6
  num_heads: 8
  emb_dim: 128
  mlp_ratio: 2

  # interpolant:
  #   min_t: 1.e-2
  #   t_normalization_clip: 0.9
  #   sample_sequence: True
  #   sample_structure: True
  #   rots:
  #     train_schedule: linear
  #     sample_schedule: exp
  #     exp_rate: 10
  #   trans:
  #     train_schedule: linear
  #     sample_schedule: linear
  #     sigma: 1.0
  #   seqs:
  #     num_classes: 20
  #     simplex_value: 5.0
  #   sampling:
  #     num_timesteps: 100
  #   self_condition: False

train:
  loss_weights:
    trans_loss: 0.5 # 1.0 for dreamfold, 0.05 for yim
    rot_loss: 0.5 # 1.0 for dreamfold, 0.5 for yim
    bb_atom_loss: 0.25
    seqs_loss: 1.0
    angle_loss: 1.0
    torsion_loss: 0.5
    vae_loss: 0.5
    commitment_loss: 0.5
    q_latent_loss: 0.5
    dist_loss: 0.25
    fape_loss: 0.05
    clash_loss: 0.10
  max_iters: 400000000
  val_freq: 5000
  batch_size: 10
  batch_size_pr: 10
  accum_grad: 1
  seed: 114514
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4 #1.e-4
    weight_decay: 1.e-9
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 5.e-6

dataset:
  train:
    type: peprec
    structure_dir: /remote-home/share/wangyu/peptide/raw
    dataset_dir: /remote-home/share/wangyu/peptide/lmdb_data
    name: pep_pocket_train
    reset: False
  val:
    type: peprec
    structure_dir: /remote-home/share/wangyu/peptide/raw
    dataset_dir: /remote-home/share/wangyu/peptide/lmdb_data
    name: pep_pocket_test
    reset: False